[package]
name = "f3blink"
version = "0.1.0"
authors = ["Ilia Motornyi <ilia.motornyi@jetbrains.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "f3blink"
crate-type = ["staticlib"]

[dependencies]